// Action Types

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RECEIVE_VOTE_POST = 'RECEIVE_VOTE_POST'
export const RECEIVE_EDIT_POST = 'RECEIVE_EDIT_POST'
export const RECEIVE_ADD_POST = 'RECEIVE_ADD_POST'
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST'

export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const RECEIVE_VOTE_COMMENT = 'RECEIVE_VOTE_COMMENT'
export const RECEIVE_EDIT_COMMENT = 'RECEIVE_EDIT_COMMENT'
export const RECEIVE_ADD_COMMENT = 'RECEIVE_ADD_COMMENT'
export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT'